### ISSUE TITLE
发现几个问题

### ISSUE THREAD

**Issue by yinjiangit** [eyesmoons/lacus#27]
1.DruidConfig @Bean(name = "dynamicDataSource") 循环依赖 本地启动需要注释掉
2.EmbeddedRedisConfig setting("maxheap 32") 无 redis 模式出现错误要将这个注释掉
3.前端代码和后端的代码元数据方面好像并没上线,不知道是不是我启动方式有问题

**Comment by eyesmoons** [comment]
感谢反馈。拉取一下代码，导入最新的数据库脚本：sql/lacus.sql。

**Comment by eyesmoons** [comment]
目前元数据、数据同步和前端交互部分都已经上线，可能会有些bug。任务启停这块目前还没有调试。

**Comment by yinjiangit** [comment]
超级棒的项目,我尝试一下
