### ISSUE TITLE
DorisSink是来一条数据就触发写入，如果频率高，doris的segment合并不及时，容易报错版本大于1000

### ISSUE THREAD

**Issue by fanqiejiang8** [eyesmoons/lacus#85]
public void invoke(Map<String, String> value, Context context) throws Exception {
        for (Map.Entry<String, String> entry : value.entrySet()) {
            DorisStreamLoad dorisStreamLoad = dorisStreamLoadMap.get(entry.getKey());
            if (dorisStreamLoad == null) {
                log.warn("未取到dorisStreamLoad配置:{}", entry.getKey());
                continue;
            }
            flush(dorisStreamLoad, entry);
        }
    }

**Comment by eyesmoons** [comment]
sink之前开窗攒批了，会一批一批处理写Doris的。
